In [11]:
import pandas as pd
from ucimlrepo import fetch_ucirepo 
from sklearn.model_selection import train_test_split

In [3]:
# fetch dataset 
communities_and_crime = fetch_ucirepo(id=183) 
  
# data (as pandas dataframes) 
X = communities_and_crime.data.features 
y = communities_and_crime.data.targets

In [7]:
X

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,PolicAveOTWorked,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop
0,8,?,?,Lakewoodcity,1,0.19,0.33,0.02,0.90,0.12,...,0.29,0.12,0.26,0.20,0.06,0.04,0.9,0.5,0.32,0.14
1,53,?,?,Tukwilacity,1,0.00,0.16,0.12,0.74,0.45,...,?,0.02,0.12,0.45,?,?,?,?,0.00,?
2,24,?,?,Aberdeentown,1,0.00,0.42,0.49,0.56,0.17,...,?,0.01,0.21,0.02,?,?,?,?,0.00,?
3,34,5,81440,Willingborotownship,1,0.04,0.77,1.00,0.08,0.12,...,?,0.02,0.39,0.28,?,?,?,?,0.00,?
4,42,95,6096,Bethlehemtownship,1,0.01,0.55,0.02,0.95,0.09,...,?,0.04,0.09,0.02,?,?,?,?,0.00,?
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1989,12,?,?,TempleTerracecity,10,0.01,0.40,0.10,0.87,0.12,...,?,0.01,0.28,0.05,?,?,?,?,0.00,?
1990,6,?,?,Seasidecity,10,0.05,0.96,0.46,0.28,0.83,...,?,0.02,0.37,0.20,?,?,?,?,0.00,?
1991,9,9,80070,Waterburytown,10,0.16,0.37,0.25,0.69,0.04,...,0.25,0.08,0.32,0.18,0.08,0.06,0.78,0,0.91,0.28
1992,25,17,72600,Walthamcity,10,0.08,0.51,0.06,0.87,0.22,...,0.19,0.03,0.38,0.33,0.02,0.02,0.79,0,0.22,0.18
1993,6,?,?,Ontariocity,10,0.20,0.78,0.14,0.46,0.24,...,0.11,0.11,0.30,0.05,0.08,0.04,0.73,0.5,1.00,0.13

In [10]:
X.describe(include='all')

,state,county,community,communityname,fold,population,householdsize,racepctblack,racePctWhite,racePctAsian,...,PolicAveOTWorked,LandArea,PopDens,PctUsePubTrans,PolicCars,PolicOperBudg,LemasPctPolicOnPatr,LemasGangUnitDeploy,LemasPctOfficDrugUn,PolicBudgPerPop
count,1994.000000,1994,1994,1994,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,1994.000000,...,1994,1994.000000,1994.000000,1994.000000,1994,1994,1994,1994,1994.000000,1994
unique,NaN,109,800,1828,NaN,NaN,NaN,NaN,NaN,NaN,...,78,NaN,NaN,NaN,64,39,73,4,NaN,52
top,NaN,?,?,Greenvillecity,NaN,NaN,NaN,NaN,NaN,NaN,...,?,NaN,NaN,NaN,?,?,?,?,NaN,?
freq,NaN,1174,1177,5,NaN,NaN,NaN,NaN,NaN,NaN,...,1675,NaN,NaN,NaN,1675,1675,1675,1675,NaN,1675
mean,28.683551,NaN,NaN,NaN,5.493982,0.057593,0.463395,0.179629,0.753716,0.153681,...,NaN,0.065231,0.232854,0.161685,NaN,NaN,NaN,NaN,0.094052,NaN
std,16.397553,NaN,NaN,NaN,2.873694,0.126906,0.163717,0.253442,0.244039,0.208877,...,NaN,0.109459,0.203092,0.229055,NaN,NaN,NaN,NaN,0.240328,NaN
min,1.000000,NaN,NaN,NaN,1.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,NaN,0.000000,0.000000,0.000000,NaN,NaN,NaN,NaN,0.000000,NaN
25%,12.000000,NaN,NaN,NaN,3.000000,0.010000,0.350000,0.020000,0.630000,0.040000,...,NaN,0.020000,0.100000,0.020000,NaN,NaN,NaN,NaN,0.000000,NaN
50%,34.000000,NaN,NaN,NaN,5.000000,0.020000,0.440000,0.060000,0.850000,0.070000,...,NaN,0.040000,0.170000,0.070000,NaN,NaN,NaN,NaN,0.000000,NaN
75%,42.000000,NaN,NaN,NaN,8.000000,0.050000,0.540000,0.230000,0.940000,0.170000,...,NaN,0.070000,0.280000,0.190000,NaN,NaN,NaN,NaN,0.000000,NaN
max,56.000000,NaN,NaN,NaN,10.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,NaN,1.000000,1.000000,1.000000,NaN,NaN,NaN,NaN,1.000000,NaN

In [8]:
y

      ViolentCrimesPerPop
0                    0.20
1                    0.67
2                    0.43
3                    0.12
4                    0.03
...                   ...
1989                 0.09
1990                 0.45
1991                 0.23
1992                 0.19
1993                 0.48

[1994 rows x 1 columns]

In [13]:
X_train, X_test, y_train, y_test = train_test_split(X, 
                                                    y, 
                                                    test_size = 0.4, 
                                                    random_state = 42)

<h1>Check Logistic regression for imbalanced data handling</h1>